"""create initial schema

Revision ID: e2c3806b0205
Revises: 
Create Date: 2026-09-09 16:26:51.355243
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e2c3806b0205'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('cognito_sub', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('cognito_sub', name=op.f('uq_users_cognito_sub'))
    )
    op.create_table('audit_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("actor_type IN ('human', 'agent', 'system')", name=op.f('ck_audit_events_audit_actor_type')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_organization_created', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('coordinator', 'viewer')", name=op.f('ck_memberships_membership_role')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name='membership_user_organization')
    )
    op.create_index('ix_memberships_organization_user', 'memberships', ['organization_id', 'user_id'], unique=False)
    op.create_table('operations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('location_name', sa.String(length=240), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'ready', 'active', 'completed', 'cancelled')", name=op.f('ck_operations_operation_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_operations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations'))
    )
    op.create_index('ix_operations_organization_date', 'operations', ['organization_id', 'event_date'], unique=False)
    op.create_table('volunteers',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('email_consent', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_consent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_volunteers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteers')),
    sa.UniqueConstraint('organization_id', 'email', name='volunteer_organization_email')
    )
    op.create_index('ix_volunteers_organization_name', 'volunteers', ['organization_id', 'display_name'], unique=False)
    op.create_table('schedule_versions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('score_details', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'published', 'superseded')", name=op.f('ck_schedule_versions_schedule_status')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_schedule_versions_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_schedule_versions_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_schedule_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_versions')),
    sa.UniqueConstraint('operation_id', 'revision', name='schedule_operation_revision')
    )
    op.create_index('ix_schedule_versions_organization_operation', 'schedule_versions', ['organization_id', 'operation_id'], unique=False)
    op.create_table('shifts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role_name', sa.String(length=120), nullable=False),
    sa.Column('required_skill', sa.String(length=120), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_shifts_shift_positive_capacity')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_shifts_shift_time_order')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_shifts_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_shifts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index('ix_shifts_organization_operation', 'shifts', ['organization_id', 'operation_id'], unique=False)
    op.create_table('volunteer_availabilities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_volunteer_availabilities_availability_time_order')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_volunteer_availabilities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('fk_volunteer_availabilities_volunteer_id_volunteers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_availabilities'))
    )
    op.create_index('ix_availabilities_organization_volunteer', 'volunteer_availabilities', ['organization_id', 'volunteer_id'], unique=False)
    op.create_table('volunteer_skills',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_volunteer_skills_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('fk_volunteer_skills_volunteer_id_volunteers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_skills')),
    sa.UniqueConstraint('volunteer_id', 'skill_name', name='volunteer_skill_name')
    )
    op.create_index('ix_skills_organization_volunteer', 'volunteer_skills', ['organization_id', 'volunteer_id'], unique=False)
    op.create_table('assignments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_version_id', sa.Uuid(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('response_status', sa.String(length=24), nullable=False),
    sa.Column('score_details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("response_status IN ('pending', 'confirmed', 'declined')", name=op.f('ck_assignments_assignment_response_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assignments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], name=op.f('fk_assignments_schedule_version_id_schedule_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_assignments_shift_id_shifts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('fk_assignments_volunteer_id_volunteers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    sa.UniqueConstraint('schedule_version_id', 'shift_id', 'volunteer_id', name='assignment_once')
    )
    op.create_index('ix_assignments_organization_version', 'assignments', ['organization_id', 'schedule_version_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_version_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('rendered_content', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'whatsapp')", name=op.f('ck_notification_outbox_notification_channel')),
    sa.CheckConstraint("mode IN ('real', 'simulated')", name=op.f('ck_notification_outbox_notification_mode')),
    sa.CheckConstraint("status IN ('pending', 'sent', 'simulated', 'failed')", name=op.f('ck_notification_outbox_notification_status')),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_notification_outbox_assignment_id_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notification_outbox_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], name=op.f('fk_notification_outbox_schedule_version_id_schedule_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_outbox')),
    sa.UniqueConstraint('idempotency_key', name='notification_idempotency_key')
    )
    op.create_index('ix_notification_outbox_organization_status', 'notification_outbox', ['organization_id', 'status'], unique=False)
    op.create_table('volunteer_responses',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_version_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('confirm', 'decline')", name=op.f('ck_volunteer_responses_response_decision')),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_volunteer_responses_assignment_id_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_volunteer_responses_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], name=op.f('fk_volunteer_responses_schedule_version_id_schedule_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_responses')),
    sa.UniqueConstraint('token_fingerprint', name='response_token_fingerprint')
    )
    op.create_index('ix_volunteer_responses_organization_assignment', 'volunteer_responses', ['organization_id', 'assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_volunteer_responses_organization_assignment', table_name='volunteer_responses')
    op.drop_table('volunteer_responses')
    op.drop_index('ix_notification_outbox_organization_status', table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index('ix_assignments_organization_version', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_skills_organization_volunteer', table_name='volunteer_skills')
    op.drop_table('volunteer_skills')
    op.drop_index('ix_availabilities_organization_volunteer', table_name='volunteer_availabilities')
    op.drop_table('volunteer_availabilities')
    op.drop_index('ix_shifts_organization_operation', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index('ix_schedule_versions_organization_operation', table_name='schedule_versions')
    op.drop_table('schedule_versions')
    op.drop_index('ix_volunteers_organization_name', table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index('ix_operations_organization_date', table_name='operations')
    op.drop_table('operations')
    op.drop_index('ix_memberships_organization_user', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_audit_events_organization_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
